### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ycjcl868** [ahmedelgabri/gatsby-plugin-klipse#1]
![image](https://user-images.githubusercontent.com/13595509/52324596-de632080-2a1c-11e9-8aeb-6bd5fddde617.png)

**Comment by ahmedelgabri** [comment]
@ycjcl868 	more context or info is going to be helpful, so please provide more context or maybe even a small reproducable steps. Thanks.

**Comment by malcolm-kee** [comment]
I actually found the root cause for this. The problem is klipse script is currently attaching its variable in `window` object, and it somehow replace the `window.io` variable, which causing the gatsby socket io js being replaced. You can see the klipse bug here: https://github.com/viebel/klipse/issues/330

**Comment by ahmedelgabri** [comment]
Thanks @malcolm-kee! will look into it soon 👍

**Comment by ahmedelgabri** [comment]
This should be fixed in `7.0.0`
